### ISSUE TITLE
I don't know why buffer error

### ISSUE THREAD

**Issue by pipecivil** [kyriesent/node-rtsp-stream#4]
buffer.js:784
    throw TypeError('value is out of bounds');
          ^
TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:784:11)
    at Buffer.writeUInt16BE (buffer.js:819:5)
    at VideoStream.onSocketConnect (/home/ubuntu/nrs/node_modules/node-rtsp-stream/lib/videoStream.js:110:18)
    at WebSocketServer.<anonymous> (/home/ubuntu/nrs/node_modules/node-rtsp-stream/lib/videoStream.js:86:19)
    at WebSocketServer.EventEmitter.emit (events.js:95:17)
    at /home/ubuntu/nrs/node_modules/node-rtsp-stream/node_modules/ws/lib/WebSocketServer.js:74:14
    at completeHybiUpgrade2 (/home/ubuntu/nrs/node_modules/node-rtsp-stream/node_modules/ws/lib/WebSocketServer.js:237:5)
    at completeHybiUpgrade1 (/home/ubuntu/nrs/node_modules/node-rtsp-stream/node_modules/ws/lib/WebSocketServer.js:262:13)
    at WebSocketServer.handleHybiUpgrade (/home/ubuntu/nrs/node_modules/node-rtsp-stream/node_modules/ws/lib/WebSocketServer.js:290:3)

**Comment by kyriesent** [comment]
Looks like you're passing in an invalid value for `options.width` or `options.height`. You should probably confirm that you're configuring correctly, configuration keys are right, etc.

**Comment by pipecivil** [comment]
Thankyou for your reply 
I will test

how about latancy

**Comment by kyriesent** [comment]
Stale issue, closing.
